# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ryan Miller
tagline:          Father | Developer | Student
description:      'Father | Developer | Student'
url:              https://ryanmiller810.github.io

author:           
  name:           'Ryan Miller'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ryanmiller810/ryanmiller810.github.io

# This is the list of pages to include in the sidebar
pages_list:
About: '/about/'
Archive: '/archive/'
Feed: '/atom.xml'
